const express=require("express"),path=require("path");const app=express(),PORT=process.env.PORT||3000,C=new Map(),TTL=600000;
app.use(express.json());app.use(express.static(path.join(__dirname,"public")));
const dec=s=>(s||"").replace(/^<!\[CDATA\[/,"").replace(/\]\]>$/,"").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").trim();
const tag=(b,n)=>{let m=b.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,"i"));return m?dec(m[1]):""}, all=(b,n)=>[...b.matchAll(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,"gi"))].map(m=>dec(m[1]));
function vol(s){let n=parseFloat(((s||"").match(/[\d.]+/)||["0"])[0]);return /M/i.test(s)?n*1e6:/K/i.test(s)?n*1e3:n}
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));function hash(s){let n=0;for(let c of s)n=(n*31+c.charCodeAt(0))>>>0;return n}
function niche(t,r=[]){let s=(t+" "+r.join(" ")).toLowerCase(),M={Beauty:["beauty","makeup","skin","hair","fashion"],Tech:["ai","phone","iphone","app","software","tech","google","apple"],Finance:["stock","crypto","bitcoin","bank","money","trading"],Gaming:["game","gaming","playstation","xbox"],Sports:["match","football","cricket","nba","tennis"],Entertainment:["movie","song","actor","trailer","series"],Business:["business","startup","company","brand","marketing"],Health:["health","fitness","diet","wellness"]};for(let[k,w]of Object.entries(M))if(w.some(x=>s.includes(x)))return k;return"General"}
function hooks(t){let a=[`Why is everyone suddenly searching for “${t}”?`,`You’re about to see “${t}” everywhere. Here’s why.`,`Before you jump on “${t}”, know these 3 things.`,`“${t}” is moving fast — here’s the opportunity most people will miss.`],i=hash(t)%a.length;return[a[i],a[(i+1)%a.length],a[(i+2)%a.length]]}
function enrich(x){let n=niche(x.title,x.related),p=n==="Beauty"?"Instagram Reels":["Sports","Gaming","Entertainment"].includes(n)?"YouTube Shorts":n==="Tech"||n==="Business"?"YouTube Shorts":"TikTok / Shorts",w=x.stage==="Exploding"?"24–72 hours":x.stage==="Early Rising"?"3–7 days":x.stage==="Rising"?"2–5 days":"Act selectively";return{...x,niche:n,platform:p,window:w,hooks:hooks(x.title),why:`Search interest is accelerating around “${x.title}”. The current live signal shows ${x.trafficText||"rising"} search activity and is classified by TrendPulse as ${x.stage.toLowerCase()}.`,action:`Create a fast explainer about why ${x.title} is trending now. Lead with what changed, then give the audience the useful or surprising angle.`,keywords:[x.title,`${x.title} explained`,`${x.title} trend`,`why is ${x.title} trending`,`${x.title} latest`],creators:["Short-form creators","Bloggers / publishers","Affiliate / content marketers"],monetization:["Tech","Beauty","Business"].includes(n)?"High":"Medium"}}
async function get(geo="IN"){geo=geo.toUpperCase().replace(/[^A-Z]/g,"").slice(0,2)||"IN";let h=C.get(geo);if(h&&Date.now()-h.at<TTL)return h.d;let r=await fetch(`https://trends.google.com/trending/rss?geo=${geo}`,{headers:{"User-Agent":"Mozilla/5.0 TrendPulse/2.0"}});if(!r.ok)throw Error("Live trend feed unavailable");let x=await r.text(),bs=[...x.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(m=>m[1]);let ts=bs.map((b,i)=>{let title=tag(b,"title"),tt=tag(b,"ht:approx_traffic")||"Rising",pub=tag(b,"pubDate")||new Date().toUTCString(),v=vol(tt),age=Math.max(0,Math.round((Date.now()-new Date(pub))/36e5)),score=clamp(Math.round(Math.min(45,Math.log10(Math.max(10,v))*10)+Math.max(5,32-age*1.4)+(/price|buy|review|launch|best|deal/i.test(title)?14:8)),42,99),stage=age<8&&score>=86?"Exploding":age<18&&score>=74?"Early Rising":age<36?"Rising":"Established";return enrich({id:`t${i}-${hash(title)}`,title,traffic:v,trafficText:tt,ageHours:age,score,growth:clamp(Math.round((score-40)*5+Math.log10(Math.max(10,v))*50),25,800),competition:v<20000&&score>=75?"Low":v<100000?"Medium":"High",stage,related:all(b,"ht:news_item_title").slice(0,3),source:"Google Trends",sourceUrl:`https://trends.google.com/trends/explore?geo=${geo}&q=${encodeURIComponent(title)}`})}).filter(t=>t.title).sort((a,b)=>b.score-a.score);let d={geo,fetchedAt:new Date().toISOString(),trends:ts};C.set(geo,{at:Date.now(),d});return d}
app.get("/api/health",(q,r)=>r.json({ok:true,version:"2.0"}));
app.get("/api/trends",async(q,r)=>{try{let d=await get(q.query.geo||"IN");r.json({...d,stats:{signals:d.trends.length,hot:d.trends.filter(x=>x.score>=80).length,lowCompetition:d.trends.filter(x=>x.competition==="Low").length,exploding:d.trends.filter(x=>x.stage==="Exploding").length}})}catch(e){r.status(502).json({error:e.message})}});
app.get("/api/post-today",async(q,r)=>{try{let d=await get(q.query.geo||"IN"),n=q.query.niche||"All",p=q.query.platform||"Any",a=d.trends.map(t=>({...t,fitScore:clamp(t.score+((n==="All"||t.niche===n)?5:0)+((p==="Any"||t.platform.includes(p.split(" ")[0]))?4:0),0,99)})).filter(t=>n==="All"||t.niche===n||t.niche==="General").sort((a,b)=>b.fitScore-a.fitScore);if(a.length<5)a=d.trends.map(t=>({...t,fitScore:t.score}));r.json({opportunities:a.slice(0,5)})}catch(e){r.status(502).json({error:e.message})}});
app.post("/api/generate",(q,r)=>{let t=String(q.body?.trend||"").trim(),p=q.body?.platform||"YouTube Shorts";if(!t)return r.status(400).json({error:"Trend required"});let h=hooks(t);r.json({hook:h[0],concept:`Explain why “${t}” is moving now, show the strongest useful angle, then end with a question.`,script:`${h[1]} Here’s what changed, why people care, and what you should know before this gets crowded.`,title:`${t}: Why This Is Trending Right Now`,caption:`${t} is gaining momentum. Here’s what changed and why it matters.`,keywords:`${t}, ${t} trend, ${t} explained, trending now, ${p}`,hashtags:`#trending #viral #trendalert #${t.replace(/[^a-z0-9]/gi,"").slice(0,24)}`,thumbnail:`Strong visual for ${t} with 2–4 words: WHY NOW?`})});
app.get("*",(q,r)=>r.sendFile(path.join(__dirname,"public","index.html")));app.listen(PORT,()=>console.log("TrendPulse V2 running on "+PORT));